services:
  - type: web
    name: labelforge-api
    runtime: python
    buildCommand: >
      pip install -r backend/requirements.txt &&
      cd backend && python manage.py collectstatic --no-input
    startCommand: >
      cd backend &&
      python manage.py migrate &&
      python manage.py seed_data &&
      gunicorn labelforge.wsgi --bind 0.0.0.0:$PORT
    disk:
      name: labelforge-db
      mountPath: /opt/render/project/src/backend/db
      sizeGB: 1
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DB_PATH
        value: /opt/render/project/src/backend/db/db.sqlite3
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
